# Generated by Django 5.0.4 on 2024-04-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='media/product')),
                ('regular_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('product_overview', models.TextField()),
                ('product_specifcation', models.TextField()),
                ('product_brochure', models.TextField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='frontend.brand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='frontend.category')),
            ],
        ),
    ]
