# Generated by Django 5.0.4 on 2024-05-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_q_boilerdata_boiler_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_boilerdata',
            name='boiler_type',
            field=models.CharField(choices=[('Central Heating & Hot Water', 'Central Heating & Hot Water'), ('Central Heating Only', 'Central Heating Only'), ('Hot Water Only', 'Hot Water Only'), ('Do not Know', 'Do not Know')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='job_type',
            field=models.CharField(choices=[('New Instalation', 'New Instalation'), ('Replacement', 'Replacement'), ('Service', 'Service'), ('Others', 'Others')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='power_usage',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Oil', 'Oil'), ('LPG', 'LPG'), ('Others', 'Others')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Others', 'Others')], default='Unspecified', max_length=255),
        ),
    ]
