# Generated by Django 5.0.4 on 2024-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_q_boilerdata_boiler_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_evdata',
            name='car_type',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('It will be delivered shortly', 'It will be delivered shortly')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='charger_type',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='installation_type',
            field=models.CharField(choices=[('Home', 'House'), ('Business Premises', 'Business Premises')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='ownership_type',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='parking_type',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='avilable_space',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('Not Sure', 'Not Sure')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='duration',
            field=models.CharField(choices=[('As Soon As Possible', 'As Soon As Possible'), ('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6+ Months', '6+ Months')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='heat_pump_type',
            field=models.CharField(choices=[('Air Source', 'Air Source'), ('Water Source', 'Water Source'), ('Ground Source', 'Ground Source'), ('Not Sure- Need advise', 'Not Sure- Need advise')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='heating_type',
            field=models.CharField(choices=[('Gas/Oil Bioler', 'Gas/Oil Bioler'), ('Electric Boiler', 'Electric Boiler'), ('Others', 'Others')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='insulation',
            field=models.CharField(choices=[('Loft Insulation', 'Loft Insulation'), ('Cavity Insulation', 'Cavity Insulation'), ('Double Window Glazing', 'Double Window Glazing'), ('Triple window Glazing', 'Triple window Glazing'), ('None of the above', 'None of the above')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='loaction_type',
            field=models.CharField(choices=[('HOME', 'HOME'), ('BUSINESS', 'BUSINESS')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='owenership_type',
            field=models.CharField(choices=[('Homeowner', 'Homeowner'), ('Tenent', 'Tenent')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='power_type',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Oil', 'Oil'), ('LPG', 'LPG'), ('Electric', 'Electric'), ('Others', 'Others')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='property_type',
            field=models.CharField(choices=[('Semi Detached', 'Semi Detached'), ('Detached', 'Detached'), ('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Terraced', 'Terraced'), ('Other', 'Other')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='radiators',
            field=models.CharField(choices=[('1-5 Radiators', '1-5 Radiators'), ('6-10 Radiators', '6-10 Radiators'), ('11-15 Radiators', '11-15 Radiators'), ('16+ Radiators', '16+ Radiators')], default='Unspecified', max_length=255),
        ),
    ]
