# Generated by Django 5.0.4 on 2024-05-04 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_q_evdata_car_type_alter_q_evdata_charger_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_evdata',
            name='car_type',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('It will be delivered shortly', 'It will be delivered shortly')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='charger_type',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'Yes')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='installation_type',
            field=models.CharField(choices=[('House', 'House'), ('Business Premises', 'Business Premises')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='ownership_type',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='parking_type',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='avilable_space',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='loaction_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Business', 'Business')], default='Unspecified', max_length=255),
        ),
        migrations.CreateModel(
            name='Q_HomeSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=255)),
                ('residency', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=255)),
                ('age_of_building', models.CharField(max_length=255)),
                ('number_of_floors', models.CharField(max_length=255)),
                ('square_footage', models.CharField(max_length=255)),
                ('number_of_people', models.CharField(max_length=255)),
                ('average_age', models.CharField(max_length=255)),
                ('usual_stay', models.CharField(max_length=255)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('formType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.q_formtype')),
            ],
        ),
    ]
