# Generated by Django 5.0.4 on 2024-05-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_q_evdata_car_type_alter_q_evdata_charger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_InfraredHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=255)),
                ('residency', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment')], default='Unspecified', max_length=255)),
                ('heating_type', models.CharField(choices=[('Gas', 'Gas'), ('Electric', 'Electric'), ('Heat Pump', 'Heat Pump'), ('Other', 'Other')], default='Unspecified', max_length=255)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('formType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.q_formtype')),
            ],
        ),
    ]
