# Generated by Django 5.0.4 on 2024-05-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_q_solar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q_solar',
            old_name='product',
            new_name='solar_type',
        ),
    ]
