# Generated by Django 5.0.4 on 2024-05-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_rename_product_q_solar_solar_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glazing_for', models.CharField(choices=[('Windows', 'Windows'), ('Doors', 'Doors'), ('Other', 'Other')], default='Unspecified', max_length=255)),
                ('ownership', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=255)),
                ('number_of_window', models.CharField(choices=[('1', '1'), ('2-5', '2-5'), ('6+', '6+')], default='Unspecified', max_length=255)),
                ('delivery', models.CharField(choices=[('Supplied & fitted', 'Supplied & fitted'), ('Supplied only', 'Supplied only')], default='Unspecified', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('formType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.q_formtype')),
            ],
        ),
    ]
